// Productos de ejemplo
export const mockProducts = [
  {
    id: "product-1",
    title: "Smartphone XYZ Pro",
    description: "El último smartphone con cámara de alta resolución y batería de larga duración.",
    price: 699.99,
    oldPrice: 799.99,
    image: "/modern-smartphone.png",
    category: "electronics",
    subcategory: "smartphones",
    sellerId: "user-2",
    sellerName: "Tech Vendor",
    rating: 4.5,
    reviews: 128,
    stock: 50,
    status: "approved",
    freeShipping: true,
    featured: true,
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-01-15T10:30:00Z",
  },
  {
    id: "product-2",
    title: 'Laptop UltraBook 15"',
    description: "Potente laptop con procesador de última generación y pantalla de alta resolución.",
    price: 1299.99,
    image: "/modern-laptop-workspace.png",
    category: "electronics",
    subcategory: "laptops",
    sellerId: "user-2",
    sellerName: "Tech Vendor",
    rating: 4.8,
    reviews: 95,
    stock: 20,
    status: "approved",
    freeShipping: true,
    featured: false,
    createdAt: "2023-01-20T14:45:00Z",
    updatedAt: "2023-01-20T14:45:00Z",
  },
  {
    id: "product-3",
    title: "Auriculares Inalámbricos",
    description: "Auriculares con cancelación de ruido y batería de larga duración.",
    price: 149.99,
    oldPrice: 199.99,
    image: "/diverse-people-listening-headphones.png",
    category: "electronics",
    subcategory: "audio",
    sellerId: "user-2",
    sellerName: "Tech Vendor",
    rating: 4.3,
    reviews: 210,
    stock: 100,
    status: "approved",
    freeShipping: true,
    featured: true,
    createdAt: "2023-02-05T09:15:00Z",
    updatedAt: "2023-02-05T09:15:00Z",
  },
  {
    id: "product-4",
    title: "Sofá Modular 3 Plazas",
    description: "Sofá cómodo y elegante para tu sala de estar.",
    price: 599.99,
    image: "/comfortable-living-room-sofa.png",
    category: "home",
    subcategory: "furniture",
    sellerId: "user-3",
    sellerName: "Home Decor Shop",
    rating: 4.4,
    reviews: 56,
    stock: 10,
    status: "approved",
    freeShipping: false,
    featured: true,
    createdAt: "2023-02-10T11:20:00Z",
    updatedAt: "2023-02-10T11:20:00Z",
  },
  {
    id: "product-5",
    title: "Juego de Sábanas Premium",
    description: "Sábanas de algodón egipcio de alta calidad.",
    price: 89.99,
    oldPrice: 119.99,
    image: "/cozy-bedsheets.png",
    category: "home",
    subcategory: "bedding",
    sellerId: "user-3",
    sellerName: "Home Decor Shop",
    rating: 4.7,
    reviews: 112,
    stock: 80,
    status: "approved",
    freeShipping: true,
    featured: false,
    createdAt: "2023-02-15T16:30:00Z",
    updatedAt: "2023-02-15T16:30:00Z",
  },
  {
    id: "product-6",
    title: "Nuevo Producto Pendiente",
    description: "Este producto está pendiente de aprobación.",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300&query=product",
    category: "electronics",
    subcategory: "accessories",
    sellerId: "user-2",
    sellerName: "Tech Vendor",
    rating: 0,
    reviews: 0,
    stock: 25,
    status: "pending",
    freeShipping: true,
    featured: false,
    createdAt: "2023-03-01T08:45:00Z",
    updatedAt: "2023-03-01T08:45:00Z",
  },
  {
    id: "product-7",
    title: "Producto Rechazado",
    description: "Este producto fue rechazado por incumplir las normas.",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300&query=rejected",
    category: "fashion",
    subcategory: "accessories",
    sellerId: "user-3",
    sellerName: "Home Decor Shop",
    rating: 0,
    reviews: 0,
    stock: 15,
    status: "rejected",
    rejectionReason: "Las imágenes no cumplen con los estándares de calidad requeridos.",
    freeShipping: false,
    featured: false,
    createdAt: "2023-03-05T10:15:00Z",
    updatedAt: "2023-03-05T10:15:00Z",
  },
]

// Usuarios de ejemplo
export const mockUsers = [
  {
    id: "user-1",
    name: "Usuario Normal",
    email: "user@example.com",
    role: "user",
    bio: "Un usuario normal de la plataforma.",
    address: "Calle Principal 123",
    phone: "123-456-7890",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "user-2",
    name: "Tech Vendor",
    email: "seller@example.com",
    role: "seller",
    bio: "Vendedor de productos electrónicos.",
    address: "Avenida Comercial 456",
    phone: "234-567-8901",
    createdAt: "2023-01-02T00:00:00Z",
    updatedAt: "2023-01-02T00:00:00Z",
  },
  {
    id: "user-3",
    name: "Home Decor Shop",
    email: "seller2@example.com",
    role: "seller",
    bio: "Vendedor de productos para el hogar.",
    address: "Plaza del Mercado 789",
    phone: "345-678-9012",
    createdAt: "2023-01-03T00:00:00Z",
    updatedAt: "2023-01-03T00:00:00Z",
  },
  {
    id: "user-4",
    name: "Admin User",
    email: "admin@example.com",
    role: "admin",
    bio: "Administrador de la plataforma.",
    address: "Calle Administrativa 101",
    phone: "456-789-0123",
    createdAt: "2023-01-04T00:00:00Z",
    updatedAt: "2023-01-04T00:00:00Z",
  },
  {
    id: "user-5",
    name: "Super Admin",
    email: "superadmin@example.com",
    role: "superadmin",
    bio: "Super administrador con acceso total.",
    address: "Avenida Central 202",
    phone: "567-890-1234",
    createdAt: "2023-01-05T00:00:00Z",
    updatedAt: "2023-01-05T00:00:00Z",
  },
]

// Carritos de ejemplo
export const mockCarts = [
  {
    userId: "user-1",
    items: [
      {
        id: "cart-item-1",
        productId: "product-1",
        title: "Smartphone XYZ Pro",
        price: 699.99,
        image: "/modern-smartphone.png",
        quantity: 1,
      },
      {
        id: "cart-item-2",
        productId: "product-3",
        title: "Auriculares Inalámbricos",
        price: 149.99,
        image: "/diverse-people-listening-headphones.png",
        quantity: 2,
      },
    ],
    totalQuantity: 3,
    totalAmount: 999.97,
    updatedAt: "2023-03-10T15:30:00Z",
  },
]

// Listas de deseos de ejemplo
export const mockWishlists = [
  {
    userId: "user-1",
    items: [
      {
        id: "wishlist-item-1",
        productId: "product-2",
        title: 'Laptop UltraBook 15"',
        price: 1299.99,
        image: "/modern-laptop-workspace.png",
      },
      {
        id: "wishlist-item-2",
        productId: "product-4",
        title: "Sofá Modular 3 Plazas",
        price: 599.99,
        image: "/comfortable-living-room-sofa.png",
      },
    ],
    updatedAt: "2023-03-12T09:45:00Z",
  },
]

// Estadísticas de ejemplo
export const mockStats = {
  // Estadísticas para vendedores individuales
  seller: {
    "user-2": {
      monthlySales: [
        { month: "Ene", sales: 1200 },
        { month: "Feb", sales: 1800 },
        { month: "Mar", sales: 1500 },
        { month: "Abr", sales: 2200 },
        { month: "May", sales: 2800 },
        { month: "Jun", sales: 2400 },
        { month: "Jul", sales: 3000 },
        { month: "Ago", sales: 2700 },
        { month: "Sep", sales: 3200 },
        { month: "Oct", sales: 3500 },
        { month: "Nov", sales: 4000 },
        { month: "Dic", sales: 4500 },
      ],
      topProducts: [
        { name: "Smartphone XYZ Pro", sales: 120 },
        { name: 'Laptop UltraBook 15"', sales: 85 },
        { name: "Auriculares Inalámbricos", sales: 210 },
        { name: "Tablet Pro 10", sales: 65 },
        { name: "Smartwatch Series 5", sales: 95 },
      ],
      totalSales: 32800,
      totalOrders: 450,
      averageOrderValue: 72.89,
    },
    "user-3": {
      monthlySales: [
        { month: "Ene", sales: 800 },
        { month: "Feb", sales: 1200 },
        { month: "Mar", sales: 1000 },
        { month: "Abr", sales: 1500 },
        { month: "May", sales: 1800 },
        { month: "Jun", sales: 1600 },
        { month: "Jul", sales: 2000 },
        { month: "Ago", sales: 1900 },
        { month: "Sep", sales: 2200 },
        { month: "Oct", sales: 2400 },
        { month: "Nov", sales: 2800 },
        { month: "Dic", sales: 3200 },
      ],
      topProducts: [
        { name: "Sofá Modular 3 Plazas", sales: 45 },
        { name: "Juego de Sábanas Premium", sales: 120 },
        { name: "Lámpara de Pie Moderna", sales: 75 },
        { name: "Mesa de Centro", sales: 35 },
        { name: "Juego de Toallas", sales: 90 },
      ],
      totalSales: 22400,
      totalOrders: 320,
      averageOrderValue: 70.0,
    },
  },

  // Estadísticas globales para administradores
  global: {
    monthlySales: [
      { month: "Ene", sales: 5000 },
      { month: "Feb", sales: 6500 },
      { month: "Mar", sales: 5800 },
      { month: "Abr", sales: 7200 },
      { month: "May", sales: 8500 },
      { month: "Jun", sales: 7800 },
      { month: "Jul", sales: 9000 },
      { month: "Ago", sales: 8700 },
      { month: "Sep", sales: 9500 },
      { month: "Oct", sales: 10200 },
      { month: "Nov", sales: 11500 },
      { month: "Dic", sales: 13000 },
    ],
    topProducts: [
      { name: "Smartphone XYZ Pro", sales: 320 },
      { name: "Auriculares Inalámbricos", sales: 280 },
      { name: "Juego de Sábanas Premium", sales: 240 },
      { name: 'Laptop UltraBook 15"', sales: 180 },
      { name: "Sofá Modular 3 Plazas", sales: 120 },
    ],
    topCategories: [
      { name: "Electrónica", sales: 45000 },
      { name: "Hogar", sales: 32000 },
      { name: "Moda", sales: 28000 },
      { name: "Libros", sales: 15000 },
      { name: "Deportes", sales: 12000 },
    ],
    totalSales: 102700,
    totalOrders: 1450,
    averageOrderValue: 70.83,
    totalUsers: 5200,
    newUsers: 320,
  },

  // Estadísticas avanzadas para superadmins
  advanced: {
    categoryPreferences: [
      { name: "Electrónica", value: 45 },
      { name: "Hogar", value: 25 },
      { name: "Moda", value: 15 },
      { name: "Libros", value: 10 },
      { name: "Deportes", value: 5 },
    ],
    purchaseFrequency: [
      { month: "Ene", value: 1.2 },
      { month: "Feb", value: 1.3 },
      { month: "Mar", value: 1.1 },
      { month: "Abr", value: 1.4 },
      { month: "May", value: 1.5 },
      { month: "Jun", value: 1.3 },
      { month: "Jul", value: 1.6 },
      { month: "Ago", value: 1.5 },
      { month: "Sep", value: 1.7 },
      { month: "Oct", value: 1.8 },
      { month: "Nov", value: 1.9 },
      { month: "Dic", value: 2.1 },
    ],
    averageSpending: [
      { month: "Ene", value: 65 },
      { month: "Feb", value: 68 },
      { month: "Mar", value: 64 },
      { month: "Abr", value: 70 },
      { month: "May", value: 72 },
      { month: "Jun", value: 69 },
      { month: "Jul", value: 75 },
      { month: "Ago", value: 73 },
      { month: "Sep", value: 78 },
      { month: "Oct", value: 80 },
      { month: "Nov", value: 85 },
      { month: "Dic", value: 90 },
    ],
    userRetention: [
      { month: "Ene", value: 65 },
      { month: "Feb", value: 68 },
      { month: "Mar", value: 64 },
      { month: "Abr", value: 70 },
      { month: "May", value: 72 },
      { month: "Jun", value: 69 },
      { month: "Jul", value: 75 },
      { month: "Ago", value: 73 },
      { month: "Sep", value: 78 },
      { month: "Oct", value: 80 },
      { month: "Nov", value: 82 },
      { month: "Dic", value: 85 },
    ],
    totalUsers: 5200,
    activeUsers: 3800,
    totalRevenue: 102700,
    conversionRate: 0.15,
  },
}
